---
# tasks file for install_wp
- name: Install wp-cli
  script: install_wp/scripts/wpcli_install.sh
  args:
    creates: /usr/local/bin/wp

- name: Install and configure WordPress
  script: install_wp/scripts/wp_install.sh
