---
- name: Install and configure LEMP and WordPress
  hosts: test_server
  become: yes
  
  roles:
    - install_packages
    - myisam_conf
    - nginx_default
    - nginx_site
    - install_wp
  handlers:
    - include: handlers/main.yml
