---
- name: Start nginx
  service:
    name: nginx
    state: started

- name: Restart nginx
  service:
    name: nginx
    state: reloaded

- name: Enable nginx
  service:
    name: nginx
    enabled: yes

- name: Start mariadb
  service:
    name: mysql
    state: started

- name: Restart mariadb
  service:
    name: mysql
    state: restarted

- name: Enable mariadb
  service:
    name: mysql
    enabled: yes
