---
- name: Start nginx
  service:
    name: nginx
    state: started

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Start mariadb
  service:
    name: mysql
    state: started

- name: Restart mariadb
  service:
    name: mysql
    state: restarted
