---
# tasks file for nginx_site

- name: Account dehydrated
  shell: dehydrated --register --accept-terms

- name: Add domain dehydrated
  lineinfile:
    dest: /etc/dehydrated/domains.txt
    line: "{{yourdomain}} www.{{yourdomain}}"
    create: yes

- name: Configure http for site
  template:
    src: domain80.conf
    dest: /etc/nginx/sites-enabled/{{yourdomain}}80.conf
  notify: Restart nginx

- name: Call notifyes
  meta: flush_handlers

#- name: Take keys for site
#  shell: dehydrated -c

- name: Make dir for local site
  shell: /var/lib/dehydrated/certs/{{yourdomain}}
  args:
    creates: "/var/lib/dehydrated/certs/{{yourdomain}}"

- name: Take keys for localsite
  expect:  
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /var/lib/dehydrated/certs/{{yourdomain}}/privkey.pem -out /var/lib/dehydrated/certs/{{yourdomain}}/fullchain.pem
    responses:
         'Country Name (2 letter code) [AU]': "BR"
         'State or Province Name (full name) [Some-State]': "City"
         'Locality Name (eg, city) []': "Mi"
         'Organization Name (eg, company) [Internet Widgits Pty Ltd]': "Home"
         'Organization Unit Name (eg, section) []': "Org"
         'Common Name (e.g. server FQDN or YOUR name) []': "Name"
         'Email Address []': "ggg@hghfssd.com"
    creates: "/var/lib/dehydrated/certs/{{yourdomain}}/fullchain.pem"
    echo: yes

- name: Configure https for site
  template:
    src: domain443.conf
    dest: /etc/nginx/sites-enabled/{{yourdomain}}443.conf
  notify: Restart nginx

- name: Auto update dehydrated step 1
  template:
    src: Dehydrated
    dest: /etc/cron.weekly/Dehydrated
    mode: 0755

- name: Auto update dehydrated step 2
  template:
    src: hook.sh
    dest: /etc/dehydrated/hook.sh
    mode: 0755
